spring.application.name=inventariofeicc

spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.idsdkpdonldeaqrfcttq
spring.datasource.password=inventariofeicc

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.configuration.map-underscore-to-camel-case=true